baseurl: "/docs" # the subpath of your site, e.g. /blog/
title: '在线金融学院'
desc: '维基知识库'
sidebar_title: '内容分类'

exclude:
- Gemfile
- Gemfile.lock
- Rakefile
- README.md
- template

# Build settings
markdown: redcarpet
redcarpet:
  extensions:
  - no_intra_emphasis
  - fenced_code_blocks
  - autolink
  - tables
  - with_toc_data
  - footnotes

collections:
  refbooks:
    output: true
    permalink: refbooks/:path/index.html
  articles:
    output: true
    permalink: articles/:title.html
  wikis:
    output: true
    permalink: wikis/:title.html
